Lineage Registration: dynamic spacial registration
mastodon-sc/mastodon-tomancak pull request #28
Opened 2023-05-08 13:00 UTC by maarzt

Closes #22

2023-05-10 12:51 UTC, stefanhahmann reviewed
This PR modifies the method how the lineage registration is done and adds new methods.

- It is important to mention that this PR is not 100% in line with the issue description (https://github.com/mastodon-sc/mastodon-tomancak/issues/22). The "fixed" option is modified. It seems to improve the registration, but is not working exactly as before, as the issue description claims, but this can be solved by providing some documentation about the three registration methods.

- It is hard to judge, if the dynamic registration really improves the registration. It seems so, but one can also find examples, where it worsens the registration.

- Since the "Color paired lineages" function is now the only function that is independent from the chosen registration, it may be moved to different dialog. Users otherwise may wonder why this function always leads to the same result, no matter, which registration method is active.

- In TrackScheme, there is a bug, when adding a new center Spot. TrackScheme needs to be refreshed with `Ctrl` + `Del` after a new center spot is added, before the user can see it in TrackScheme.

- Regarding registration with the "landmarks" tag set: the documentation should inform users that in case of multiple "landmarks" tag set, the first one is chosen by the algorithm.

- Please consider renaming "spa*c*ial" to "spa*t*ial". Both versions of the word exist, but the version with 't' seems to be the more common one

2023-05-24 14:48 UTC, maarzt commented
@stefanhahmann Thank you for testing the code and sharing your opinions. I agree with your concerns. Some problems are fixed now. Here are my replies to the individual points. I think the PR is good enough to be merged now.

> - It is important to mention that this PR is not 100% in line with the issue description (https://github.com/mastodon-sc/mastodon-tomancak/issues/22). The "fixed" option is modified. It seems to improve the registration, but is not working exactly as before, as the issue description claims, but this can be solved by providing some documentation about the three registration methods.

That's true. There is a small different between the old behavior and the "fixed spacial registration" option. The old behavior used spot coordinates on timepoint 0 for registration. The new behavior uses coordinates of the root cells just before cell division.

> - It is hard to judge, if the dynamic registration really improves the registration. It seems so, but one can also find examples, where it worsens the registration.

I agree that it is hard to judge. But there are reasons to believe that the dynamic registration works better:
* Some embryos rotate. For them the fixed registration is expected to be worse. The unit test [DynamicLandmarkRegistrationTest](https://github.com/mastodon-sc/mastodon-tomancak/blob/dynamic-spacial-registration/src/test/java/org/mastodon/mamut/tomancak/lineage_registration/spatial_registration/DynamicLandmarkRegistrationTest.java) demonstrates that the "dynamic registration" works on a artificial rotating dataset where "fixed registration" would fail.
* I did a quantitative comparison by measuring angles between cell division directions between the two embryos. I did this across all dataset that I had available. "dynamic registration" led to slightly smaller angles on average. (Smaller angles is better). The difference is small, and for some datasets the angles actually worsened. I unfortunately lost the code for this comparison :facepalm: 

> - Since the "Color paired lineages" function is now the only function that is independent from the chosen registration, it may be moved to different dialog. Users otherwise may wonder why this function always leads to the same result, no matter, which registration method is active.

I agree with your concerns. But a separate dialog, where you select dataset and timepoints, is not worth the struggle. Lets instead write documentation that makes things clear.

> - In TrackScheme, there is a bug, when adding a new center Spot. TrackScheme needs to be refreshed with `Ctrl` + `Del` after a new center spot is added, before the user can see it in TrackScheme.

Fixed in [#e1dce454c1cf3eba6ebfb4888dbb38f4cad6b4ef](https://github.com/mastodon-sc/mastodon-tomancak/pull/28/commits/e1dce454c1cf3eba6ebfb4888dbb38f4cad6b4ef)

> - Regarding registration with the "landmarks" tag set: the documentation should inform users that in case of multiple "landmarks" tag set, the first one is chosen by the algorithm.

I agree.

> - Please consider renaming "spa*c*ial" to "spa*t*ial". Both versions of the word exist, but the version with 't' seems to be the more common one

done

2023-05-30 10:50 UTC, stefanhahmann requested changes
There is a comment in a related PR that does not seem to have been addressed:
https://github.com/mastodon-sc/mastodon-tomancak/pull/27#discussion_r1193658174

The CI seems to fail on DynamicLandmarkRegistrationTest.testLineageRegistrationAlgorithm()
It is not clear to me, if this is related to this PR or perhaps to https://github.com/mastodon-sc/mastodon/issues/225
Could you please check?

2023-06-01 10:16 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationUtils.java
>  	 * The sorting is based on the result of the
Thank you for spotting this it's fixed now.

2023-06-01 10:16 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/RefCollectionUtils.java
> +import org.mastodon.collection.RefRefMap;
Thank you for spotting this. It's fixed now.

2023-06-01 11:39 UTC, merged