Collaboration Tools
mastodon-sc/mastodon-tomancak pull request #47
Opened 2023-09-28 14:04 UTC by maarzt

This is currently a prototype to solve #42 #43

This PR adds new menu items in Mastodon, that allow to share a Mastodon dataset, and to collaborate on it.
![image](https://github.com/mastodon-sc/mastodon-tomancak/assets/24407711/10ee4711-59cf-4c90-8346-4ff140aa5464)

2023-09-28 14:13 UTC, maarzt commented
@stefanhahmann Could you please test if the Mastodon git integration works:
* Clone this test repo: https://github.com/maarzt/mgit-test
* Make a change & commit
* Push the commit

I'm looking forward to get your feedback.

2023-11-08 15:13 UTC, stefanhahmann requested changes
This PR adds a bunch of functionalities needed for the git approach to Mastodon collaborative. The added features seem to be very useful.

It is a bit unfortunate that the test coverage for the logic contained in it is so low. This would make it hard to make changes in this repository for new developers in the future. You may consider to increase test coverage.

Apart from that I have mainly some comments on some terms shown to the user on the UI side and the user feedback on some specific workflows.

2023-11-09 13:56 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/credentials/PersistentCredentials.java
> +	private boolean missingCredentials()
Addressed in 1bec3102ac2ff49e279bb779e1a96919f66420aa

2023-11-10 11:16 UTC, masgitoff commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/credentials/PersistentCredentials.java
> +public class PersistentCredentials
Fixed in commit 97c225e52667a9f43ff76bf6931e8f1d77c76748

2023-11-10 11:27 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/credentials/PersistentCredentials.java
> +public class PersistentCredentials
Fixed in commit https://github.com/mastodon-sc/mastodon-tomancak/commit/6d773fdcd0d309172c73048b1b42d3a36abed015

2023-11-10 11:29 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/commands/MastodonGitCloneRepository.java
> +			ErrorDialog.showErrorMessage( "Download Shares Project (Clone)", e );
fixed

2023-11-10 14:20 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/commands/NewDirectoryUtils.java
> +			if ( directory.list().length > 0 )
I get this error message in my IDE too. But it's a false positive as it points to an non existing problem. The File.list() returns null only if the file is not a directory, but in line 58 I make sure that it is in fact a directory.

2023-11-10 14:21 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/commands/NewDirectoryUtils.java
> +				throw new IOException( "Directory already exists and is not empty: " + directory );
done

2023-11-10 14:24 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/commands/MastodonGitCloneRepository.java
> +		}
Fixed in 050375b43acbf4d5ed5cdc5a34674b59eba970e0

The stack trace is no longer written to the console. It instead can be shown by clicking on details in the error message dialog:
![image](https://github.com/mastodon-sc/mastodon-tomancak/assets/24407711/c8b60006-0560-4a22-b9cd-bb09aa2130e2)

2023-11-10 15:54 UTC, stefanhahmann commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/commands/NewDirectoryUtils.java
> +			if ( directory.list().length > 0 )
I disagree that this was a false positive.

According to documentation, there are two reasons why `File.list()` may return `null`.

- File is not a directory (which you checked)
- There as an I/O error while reading the directory (probably a rare case, but it was not checked)

Cf.:
![grafik](https://github.com/mastodon-sc/mastodon-tomancak/assets/10515534/f06aaf49-e0f3-4fa5-9b42-1884a0680ceb)

2023-11-13 15:40 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/utils/ConflictUtils.java
> +	private static boolean isTagSetEmpty( TagSetModel< Spot, Link > tagSetModel, String tagSetName, String tagLabel )
Hm. The behavior of the class is "Returns true if the tag set is empty or if it does not exist."
I would keep this method here like that.
A method in TagSetUtils should throw a NoSuchElement exception if the tag set does not exist.

2023-11-13 15:43 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/ErrorDialog.java
> +		e.printStackTrace();
I guess it's the most commonly accepted way to print a strack trace in scijava / Fiji.

2023-11-13 15:45 UTC, stefanhahmann commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/MastodonGitController.java
> +			"Plugins > Git > Initialize > Share Project",
I know that "Plugins > Collaborative" exists. This is why I suggested "Plugins > Collaborative **_(Git)_**"
I would argue that this name is more self-explaining to less technically people trained people, while it is still distinctive to the already existing Collaborative tools.

2023-11-13 15:53 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/collaboration/MastodonGitController.java
> +			"Plugins > Git > Initialize > Share Project",
I agree with you. I even renamed the entry in the Fiji menu to "Plugins > Mastodon Collaborative (Git)". So it makes sense to rename it here as well.

2024-01-02 10:35 UTC, maarzt commented
The classes in the PR where moved to a new repository https://github.com/maarzt/mastodon-git

2024-01-02 10:35 UTC, closed without merging