LineageRegistrationPlugin: add copy spot labels functionality
mastodon-sc/mastodon-tomancak pull request #61
Opened 2024-06-14 13:38 UTC by maarzt

issue #60

2024-06-25 13:22 UTC, stefanhahmann requested changes
I tested the function and it mainly worked as expected with one inconsistency:

Currently, the branch graph shows the label of the last spot that belongs to it, making the label of the *last* spot the significant label of the branch. This copy label function uses the label of the *first* spot to copy it to all spots of equivalent branch in the other project. This is okay, as long as users only work on the branch graph, but may lead to inconsistent / unexpected behavior, if the users use both, the branch graph and the spot graph.

I recommend some action to overcome this inconsistency.

2024-06-25 13:22 UTC, stefanhahmann commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationFrame.java
> +			+ "Labels on individual spot can not copied."
```suggestion
			+ "Labels of individual spot can not copied."
```

2024-06-25 13:22 UTC, stefanhahmann commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationFrame.java
> +			+ "The correspondences are on a level of cells / branches.<br>"
```suggestion
			+ "The correspondences are on the level of cells / branches.<br>"
```

2024-07-02 15:15 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationUtils.java
> +				boolean hasLabel = !Integer.toString( spotA.getInternalPoolIndex() ).equals( spotA.getLabel() );
I opened a PR https://github.com/mastodon-sc/mastodon/pull/318 that addresses this suggestion.

2024-07-02 15:34 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationFrame.java
> +		add( new JLabel( "Copy spot labels:" ) );
The text says now "copy spot labels"

2024-07-02 15:34 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationFrame.java
> +			+ "Labels on individual spot can not copied."
It's corrected.

2024-07-02 15:35 UTC, maarzt commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationFrame.java
> +			+ "The correspondences are on a level of cells / branches.<br>"
Thank you for spotting this.

2024-07-02 15:36 UTC, merged

2024-07-18 09:32 UTC, stefanhahmann commented on src/main/java/org/mastodon/mamut/tomancak/lineage_registration/LineageRegistrationUtils.java
> +				boolean hasLabel = !Integer.toString( spotA.getInternalPoolIndex() ).equals( spotA.getLabel() );
@maarzt https://github.com/mastodon-sc/mastodon/pull/318 has been merged in the meantime. Thus you could update here.